// Instantly Clone - PM2 Ecosystem Configuration
// Auto-generated by Claude Code Elite
// Next.js app running on port 4000
// Start: pm2 start ecosystem.config.js

module.exports = {
  apps: [
    {
      name: 'instantly-clone',
      script: 'npm',
      args: 'run dev',
      cwd: './',
      watch: false,
      env: {
        NODE_ENV: 'development',
        PORT: 4000,
      },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
    },
  ],
};
